import re
from dataclasses import dataclass, field
from typing import Dict, List, Tuple

@dataclass
class Span:
    type: str
    start: int
    end: int
    value: str

@dataclass
class TokenVault:
    _vault: Dict[str, str] = field(default_factory=dict)
    _reverse_vault: Dict[str, str] = field(default_factory=dict)
    _counters: Dict[str, int] = field(default_factory=dict)

    def tokenize(self, entity_type: str, value: str) -> str:
        if value in self._reverse_vault:
            return self._reverse_vault[value]
        
        self._counters[entity_type] = self._counters.get(entity_type, 0) + 1
        token = f"<{entity_type}_{self._counters[entity_type]:03d}>"
        self._vault[token] = value
        self._reverse_vault[value] = token
        return token

    def detokenize(self, text: str) -> str:
        # Only restore known generated tokens
        for token, value in self._vault.items():
            text = text.replace(token, value)
        return text

    def get_raw_values(self) -> List[str]:
        return list(self._vault.values())

# Simple deterministic detection
# In a real bank, this would be robust regex + NER rules.
PATTERNS = {
    "EMAIL": r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+",
    "PHONE": r"\+?\d{1,3}[-.\s]?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}",
    "EMPLOYEE_ID": r"EMP-\d{5}",
    "ACCOUNT_NO": r"\b\d{9}\b",
    "APPLICATION_ID": r"\b\d{6}\b|LN-\d{4}-\d{4}",
    "PERSON": r"\b(?:Rahul Sharma|Priya Patel|Amit Verma)\b" # Focused regex for demo to avoid false positives
}

# Policy rules
REDACT_TYPES = {"EMPLOYEE_ID"} # Types that are always redacted (irrelevant for tasks)
TOKENIZE_TYPES = {"PERSON", "APPLICATION_ID", "ACCOUNT_NO", "EMAIL", "PHONE"}

def detect_sensitive_spans(text: str) -> List[Span]:
    spans = []
    # To avoid overlapping issues, we process in a specific order or just gather all
    # For simplicity, we just run all regexes and collect non-overlapping spans
    for entity_type, pattern in PATTERNS.items():
        for match in re.finditer(pattern, text):
            # Very simplistic overlap check could be added here
            spans.append(Span(type=entity_type, start=match.start(), end=match.end(), value=match.group()))
    
    # Sort by start position
    spans.sort(key=lambda x: x.start)
    return spans

def sanitize_input(text: str, vault: TokenVault) -> str:
    """Redacts irrelevant data and tokenizes necessary data."""
    spans = detect_sensitive_spans(text)
    if not spans:
        return text

    # Process from right to left to avoid index shifting
    result = text
    for span in reversed(spans):
        if span.type in REDACT_TYPES:
            replacement = "[REDACTED]"
        else:
            replacement = vault.tokenize(span.type, span.value)
        
        result = result[:span.start] + replacement + result[span.end:]
        
    return result

def inspect_outbound_payload(payload: str, vault: TokenVault) -> Tuple[bool, str]:
    """Defense in depth: fail closed if raw sensitive data is found."""
    # 1. Check if any raw value from the vault leaked
    for raw_val in vault.get_raw_values():
        if raw_val in payload:
            return False, "BLOCKED: Raw token value found in outbound payload."
            
    # 2. Check if new undetected PII is somehow generated by agent
    spans = detect_sensitive_spans(payload)
    if spans:
        return False, f"BLOCKED: Sensitive data ({spans[0].type}) found in outbound payload."
        
    return True, "SAFE"

def inspect_response_and_detokenize(text: str, vault: TokenVault) -> str:
    """Validates response safety and detokenizes."""
    # We could do a DLP scan here to redact unexpected PII before detokenizing
    spans = detect_sensitive_spans(text)
    
    # Redact any newly surfaced sensitive info that wasn't a token
    # Be careful not to redact the tokens themselves (they don't match the regexes)
    result = text
    for span in reversed(spans):
        result = result[:span.start] + "[REDACTED]" + result[span.end:]
        
    # Finally detokenize known tokens
    return vault.detokenize(result)
